#!/usr/bin/env node
// docs/changelog.md from specs/: one section per API version, newest first,
// listing what that version changed (info.x-changes, written by the
// platform's release list). Generated -- the file says so at the top.
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

import {readSpec, specVersions} from './specs.mjs';

export const CHANGELOG_PATH = new URL('../docs/changelog.md', import.meta.url).pathname;

export function render(versions, read = readSpec) {
  const sections = versions.map((v, i) => {
    const changes = read(v)?.info?.['x-changes'] ?? [];
    const label = i === 0 ? `${v} (current)` : v;
    const body = changes.length
      ? changes.map((c) => `- ${c}`).join('\n')
      : i === versions.length - 1
        ? '- Baseline. The shape every unpinned request receives; it never changes.'
        : '- No shape changes recorded.';
    const link = '/api';
    return `## ${label}\n\n${body}\n\nReference: [${v}](${link}) (pick it in the document switcher) · [openapi.json](https://sepetak.com/openapi.json?version=${v})\n`;
  });
  return [
    '---',
    'title: Changelog',
    'description: What each API version changed. Generated from the OpenAPI documents.',
    'sidebar_position: 9',
    '---',
    '',
    '{/* GENERATED by scripts/changelog.mjs from specs/*.json. Edit the platform release list, not this file. */}',
    '',
    '# Changelog',
    '',
    'Each API version is a date. Pin one with `X-API-Version`; an unpinned request gets the baseline.',
    'Old versions stay served. See [Versions](/guide/versions).',
    '',
    ...sections,
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(CHANGELOG_PATH, render(specVersions()));
  console.log('wrote docs/changelog.md');
}
